%% participant info

% group = 'C';
% participantNum = 'p1';

%% load preprocessed dataset

EEG1 = pop_loadset('filename',['PP_participant_' participantNum '.set'], ...
                  'filepath',['C:\\MATLAB\\exp_1\\results\\EEG\\' group '\\participant_' participantNum '\\']);

%% Automated rejection

% EEG = pop_clean_rawdata(EEG, 'FlatlineCriterion',5, ...
%                              'ChannelCriterion',0.8, ...
%                              'LineNoiseCriterion',4, ...
%                              'Highpass','off', ...
%                              'BurstCriterion',20, ...
%                              'WindowCriterion',0.25, ...
%                              'BurstRejection','on', ...
%                              'Distance','Euclidian', ...
%                              'WindowCriterionTolerances',[-Inf 7] );
EEG = pop_clean_rawdata(EEG1, 'FlatlineCriterion',5, ...
                             'ChannelCriterion',0.8, ...
                             'LineNoiseCriterion',4, ...
                             'Highpass','off', ...
                             'BurstCriterion','off', ...
                             'WindowCriterion','off', ...
                             'BurstRejection','off', ...
                             'Distance','Euclidian');
% Visualise removed channels (TAKE NOTE)
vis_artifacts(EEG, EEG1);

% , ...
%                              'channels_ignore',{'EXG3','EXG4','EXG5','EXG6','EXG7','EXG8'}
%% Save dataset

[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'setname','Data Bad Channels/Data Removed','gui','off'); 
EEG = pop_saveset(EEG, 'filename',['RBC_participant_' participantNum '.set'], ...
                       'filepath',['C:\\MATLAB\\exp_1\\results\\EEG\\' group '\\participant_' participantNum '\\']);

eeglab redraw




