---
title: "exp_1_pilot"
author: "Leonardo Sutandi"
date: "2024-05-14"
output: pdf_document
---

# This script combines 4 blocks to 1 dataset for each participant (DON'T FORGET TO CHANGE ID)

## R Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstatix)
library(flextable)
library(patchwork)

```

## Dataset Configuration
```{r, include=FALSE}

# Participant Number (MA_ / MO_ / C_)
group = "MA"
ID = "participant_11"

# MA / MO / C
block_1 <- read_csv("C:/MATLAB/exp_1/results/BEH/MA/participant_11/block_1.csv")
block_2 <- read_csv("C:/MATLAB/exp_1/results/BEH/MA/participant_11/block_2.csv")
block_3 <- read_csv("C:/MATLAB/exp_1/results/BEH/MA/participant_11/block_3.csv")
block_4 <- read_csv("C:/MATLAB/exp_1/results/BEH/MA/participant_11/block_4.csv")
block_5 <- read_csv("C:/MATLAB/exp_1/results/BEH/MA/participant_11/block_5.csv")

# Merge each participant's blocks
all <- full_join(block_1, block_2) |>
          full_join(block_3) |>
          full_join(block_4) |>
          full_join(block_5) |>
            add_column(id = ID) |>
            add_column(group = group) |>
            select(id, everything()) |> 
            select(group, everything()) # Move ID to front col1

# Set all matrices from numeric to character
all$fixJitData <- as.character(all$fixJitData)
all$cueJitData <- as.character(all$cueJitData)
all$trialType <- as.character(all$trialType) # 0 = NoGrat; 1 = Grat > CHANGE TO LABEL
all$cuePos <- as.character(all$cuePos) # 0 = left; 1 = right; 2 = Neutral > CHANGE TO LABEL
all$targetLR <- as.character(all$targetLR) # 0 = left; 1 = right > CHANGE TO LABEL
all$gapLoc <- as.character(all$gapLoc) # specific gap location
all$validity <- as.character(all$validity) # 0 = invalid; 1 = valid  > CHANGE TO LABEL
all$correctDet <- as.character(all$correctDet) # 0 = incorrect; 1 = correct > CHANGE TO LABEL
all$correctAcc <- as.character(all$correctAcc) # 0 = incorrect; 1 = correct > CHANGE TO LABEL

# Relabel (in case of filter, easier to id)
all <- all |>
  # trialType
  mutate(trialType = recode(trialType, "0" = "NG", "1" = "G")) |>
  # cuePos
  mutate(cuePos = recode(cuePos, "0" = "Left", "1" = "Right", "2" ="Neutral")) |>
  # targetLR
  mutate(targetLR = recode(targetLR, "0" = "left", "1" = "right")) |>
  # validity
  mutate(validity = recode(validity, "0" = "invalid", "1" = "valid", "2" = "neutral")) |>
  # correctDet
  mutate(correctDet = recode(correctDet, "0" = "incorrect", "1" = "correct")) |>
  # correctAcc
  mutate(correctAcc = recode(correctAcc, "0" = "incorrect", "1" = "correct"))


  


# add z-score for each rtDet
all <- all |>
  add_column (zscore = ((all$rtDet - mean(all$rtDet) / sd(all$rtDet)))) |>
  filter(zscore < 3)
# only select rtDet with zscore < 3

# Save participant X's merged dataset (all blocks) for final participants' merge
write_csv(all, "C:/R/exp_1/results/BEH/indv_merge_dataset/MA_11.csv")


```

## Validity Reaction Time PLot - Correct Responses Only
```{r}
# NoGrat
noGratRt <- filter(all,
                   trialType == 0,  # Only want NoGrat
                   correctDet == 1) # Only want correct response
# Set plot contents
noGratRt <- ggplot(noGratRt, aes(validity, rtDet, fill = validity)) + 
              # Set plot design
              geom_boxplot(alpha = 0.5) +
              # Set major labels (title, Y, X axis)
              labs(title = "Reaction Time (Detection response)",
                   x = "No Gratings", 
                   y = "RT (Secs)") +
              # Rename each X axis character label
              scale_x_discrete(labels = c("Invalid", "Valid", "Neutral")) +
              # Set Y axis range
              #ylim(0, .75) +
              # Set colour
              scale_fill_manual(values=c("coral", "cadetblue1", "seagreen1")) +
              # Plot theme
              theme_bw() +
              # Remove legend
              guides(fill=FALSE)


# Gratings
gratRt <- filter(all,
                 trialType == 1,
                 correctDet == 1)
# Set plot contents
gratRt <- ggplot(gratRt, aes(validity, rtDet, fill = validity)) + 
            # Set plot design
            geom_boxplot(alpha = 0.5) +
            # Set major labels (title, Y, X axis)
            labs(title = "",
                 x = "Gratings", 
                 y = "") +
            # Rename each X axis character label
            scale_x_discrete(labels = c("Invalid", "Valid", "Neutral")) +
            # Set Y axis range
            #ylim(0, .75) +
            # Set colour
            scale_fill_manual(values=c("coral", "cadetblue1", "seagreen1")) +
            # Plot theme
            theme_bw() +
            # Remove legend
            guides(fill=FALSE)

rtPlot = noGratRt + gratRt
# ggsave("C:/MATLAB/exp_1/results/figures/RT_plot.png", rtPlot)
print(rtPlot)
```

## Summary Descriptive
```{r}
all|>
  group_by(validity, targetLR, trialType) |>
  get_summary_stats(rtDet, type = "mean_sd") |>

  flextable(cwidth = .95) |>
  fontsize(size = 8) |>
  fontsize(size = 10, part = "header") |>

  set_header_labels(validity = "Validity",
                    targetLR = "Left/Right Target",
                    trialType = "Gratings",
                    variable = "Variable")
```

# Outliers
```{r}
# IQR Method (rstatix)
# is.outlier = values ABOVE Q3 + 1.5xIQR or BELOW Q1 - 1.5xIQR
# is.extreme = values ABOVE Q3 + 3xIQR or BELOW Q1 - 3xIQR

# Identify outlier
IQR <- all|>
  identify_outliers(rtDet)
# Identify all rtDet classified as extreme outlier
IQR1 <- c(IQR$rtDet[IQR$is.extreme == TRUE])
# Remove rows with extreme outlier based on above
allIQR <- all|>
  filter(!rtDet %in% IQR1[])

# # Z-Score Method
# # add z-score for each rtDet
# all <- all |>
#   add_column (zscore = ((all$rtDet - mean(all$rtDet) / sd(all$rtDet)))) |>
# # only select rtDet with zscore < 3
#   filter(zscore < 3)



# # Save participant X's merged dataset (all blocks) for final participants' merge
# write_csv(all, "C:/R/exp_1/results/BEH/indv_merge_dataset/MA_11.csv")
```



























