---
title: "lme4"
author: "Leonardo Sutandi"
date: "2024-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# library(fs)
```

```{r}
# filePath <- dir_ls("C:/MATLAB/exp_1/results/EEG/STUDY/within/")

```

#Load within dataset
# Control

``` {r setup, include=FALSE}
# Control
# No Gratings
C_NG_Left_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Left_left_Occ.csv")
C_NG_Left_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Left_right_Occ.csv")
C_NG_Left_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Left_left_Par.csv")
C_NG_Left_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Left_right_Par.csv")

C_NG_Right_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Right_left_Occ.csv")
C_NG_Right_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Right_right_Occ.csv")
C_NG_Right_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Right_left_Par.csv")
C_NG_Right_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Right_right_Par.csv")

C_NG_Neutral_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Neutral_left_Occ.csv")
C_NG_Neutral_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Neutral_right_Occ.csv")
C_NG_Neutral_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Neutral_left_Par.csv")
C_NG_Neutral_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_NG_Neutral_right_Par.csv")

# Gratings
C_G_Left_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Left_left_Occ.csv")
C_G_Left_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Left_right_Occ.csv")
C_G_Left_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Left_left_Par.csv")
C_G_Left_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Left_right_Par.csv")

C_G_Right_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Right_left_Occ.csv")
C_G_Right_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Right_right_Occ.csv")
C_G_Right_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Right_left_Par.csv")
C_G_Right_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Right_right_Par.csv")

C_G_Neutral_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Neutral_left_Occ.csv")
C_G_Neutral_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Neutral_right_Occ.csv")
C_G_Neutral_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Neutral_left_Par.csv")
C_G_Neutral_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_C_G_Neutral_right_Par.csv")
```

# Merge dataset

```{r}
# Individual average
# merge into 1 complete 2D dataset (avg value x participants)
                     #NG
                     # Right Occipital
C_collapsed <- full_join(C_NG_Left_rightOcc, 
                               C_NG_Right_rightOcc, by = "Row") |>
                     full_join(C_NG_Neutral_rightOcc, by = "Row") |>
                     # Left Occipital
                     full_join(C_NG_Left_leftOcc, by = "Row") |>
                     full_join(C_NG_Right_leftOcc, by = "Row") |>
                     full_join(C_NG_Neutral_leftOcc, by = "Row") |>
                     # Right Parietal
                     full_join(C_NG_Left_rightPar, by = "Row") |>
                     full_join(C_NG_Right_rightPar, by = "Row") |>  
                     full_join(C_NG_Neutral_rightPar, by = "Row") |>
                     # Left Parietal
                     full_join(C_NG_Left_leftPar, by = "Row") |>
                     full_join(C_NG_Right_leftPar, by = "Row") |>
                     full_join(C_NG_Neutral_leftPar, by = "Row") |>
                     # G
                     # Right Occipital
                     full_join(C_G_Left_rightOcc, by = "Row") |>
                     full_join(C_G_Right_rightOcc, by = "Row") |>
                     full_join(C_G_Neutral_rightOcc, by = "Row") |>
                     # Left Occipital
                     full_join(C_G_Left_leftOcc, by = "Row") |>
                     full_join(C_G_Right_leftOcc, by = "Row") |>
                     full_join(C_G_Neutral_leftOcc, by = "Row") |>
                     # Right Parietal
                     full_join(C_G_Left_rightPar, by = "Row") |>
                     full_join(C_G_Right_rightPar, by = "Row") |>  
                     full_join(C_G_Neutral_rightPar, by = "Row") |>
                     # Left Parietal
                     full_join(C_G_Left_leftPar, by = "Row") |>
                     full_join(C_G_Right_leftPar, by = "Row") |>
                     full_join(C_G_Neutral_leftPar, by = "Row") |>
  add_column(group = "C") |>
  select(group, everything()) # Move ID to front col1
  names(C_collapsed)[names(C_collapsed) == "Row"] <- "id"
  
# Save  
write_csv(C_collapsed, "C:/R/exp_1/results/eeg/C_collapsed.csv")


```


# Migraine with Aura (MA)

```{r setup, include=FALSE}
# # No gratings
# MA_NG_Left_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_leftOcc.csv")
# MA_NG_Left_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_rightOcc.csv")
# MA_NG_Left_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_leftPar.csv")
# MA_NG_Left_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_rightPar.csv")
# 
# MA_NG_Right_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_leftOcc.csv")
# MA_NG_Right_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_rightOcc.csv")
# MA_NG_Right_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_leftPar.csv")
# MA_NG_Right_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_rightPar.csv")
# 
# MA_NG_Neutral_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_leftOcc.csv")
# MA_NG_Neutral_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_rightOcc.csv")
# MA_NG_Neutral_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_leftPar.csv")
# MA_NG_Neutral_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_rightPar.csv")
# 
# # Gratings
# MA_G_Left_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_leftOcc.csv")
# MA_G_Left_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_rightOcc.csv")
# MA_G_Left_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_leftPar.csv")
# MA_G_Left_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_rightPar.csv")
# 
# MA_G_Right_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_leftOcc.csv")
# MA_G_Right_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_rightOcc.csv")
# MA_G_Right_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_leftPar.csv")
# MA_G_Right_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_rightPar.csv")
# 
# MA_G_Neutral_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_leftOcc.csv")
# MA_G_Neutral_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_rightOcc.csv")
# MA_G_Neutral_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_leftPar.csv")
# MA_G_Neutral_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_rightPar.csv")
```

# Merge dataset

```{r}

```


# Migraine without Aura (MO)

``` {r setup, include=FALSE}
# # No Gratings
# MA_NG_Left_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_leftOcc.csv")
# MA_NG_Left_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_rightOcc.csv")
# MA_NG_Left_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_leftPar.csv")
# MA_NG_Left_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Left_rightPar.csv")
# 
# MA_NG_Right_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_leftOcc.csv")
# MA_NG_Right_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_rightOcc.csv")
# MA_NG_Right_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_leftPar.csv")
# MA_NG_Right_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Right_rightPar.csv")
# 
# MA_NG_Neutral_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_leftOcc.csv")
# MA_NG_Neutral_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_rightOcc.csv")
# MA_NG_Neutral_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_leftPar.csv")
# MA_NG_Neutral_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_NG_Neutral_rightPar.csv")
# 
# # Gratings
# MA_G_Left_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_leftOcc.csv")
# MA_G_Left_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_rightOcc.csv")
# MA_G_Left_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_leftPar.csv")
# MA_G_Left_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Left_rightPar.csv")
# 
# MA_G_Right_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_leftOcc.csv")
# MA_G_Right_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_rightOcc.csv")
# MA_G_Right_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_leftPar.csv")
# MA_G_Right_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Right_rightPar.csv")
# 
# MA_G_Neutral_leftOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_leftOcc.csv")
# MA_G_Neutral_rightOcc <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_rightOcc.csv")
# MA_G_Neutral_leftPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_leftPar.csv")
# MA_G_Neutral_rightPar <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/within/within_MA_G_Neutral_rightPar.csv")
```

# Merge dataset

```{r}

```


# Load Between Dataset
#between <- read_csv("C:/MATLAB/exp_1/results/EEG/STUDY/between/")














































