---
title: "lmer_2"
author: "Leonardo Sutandi"
date: "2024-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstatix)
library(lme4)
```

# LMM Instruction

```{r, include = FALSE}

# lmer(outcome ~ 1 + predictor + (1|participant) + (1|item), data = data)
# 
# random effects = interior parentheses (1|X) > participant, item; left of | vary by grouping factor on right |
# fixed effect =  not in parentheses > outcome, predictor
# 
# Statistical plan 
# separated for each attentional orienting groups - cuePos (Left vs Right) for each ROI:
#
# - Random effects: participants
# - Fixed effects: Groups (C vs MA vs MO), trialType (NG vs G)
```

# Behavioural Data

```{r, include = FALSE}

lmer(rtDet ~ 1 + group + trialType + cuePos + (1|id), data = data)

```

# Select Comparisons

```{r}
# Change for every comparisons

data <- fullData |>
  filter(cuePos == "Left",
         hemis == "right",
         ROI == "Occ")

```


# EEG Data

```{r}

# Do this for each ROI(4) in each cuePos(2, with or without neutral subtraction??)

lmer(alpha ~ 1 + group + trialType + (1|id), data = data)

```





















































